"""Lightweight V2 perceptual domain contracts.

The NumPy auditory runtime remains in ``noisyne.perception.auditory`` so this
package import stays lightweight. No loudness, masking, descriptor, playback,
or translation algorithm is implemented here.
"""

from .auditory_contracts import (
    AUDITORY_FRONTEND_METHOD_ID,
    AUDITORY_FRONTEND_METHOD_VERSION,
    AUDITORY_FRONTEND_SCHEMA_VERSION,
    AuditoryFrontendConfig,
    AuditoryFrontendSummary,
)
from .common import (
    AuditoryBand,
    ComponentStatus,
    Confidence,
    ConfidenceBasis,
    EvidenceSource,
    FrequencyRange,
    Measurement,
    MethodMetadata,
    ObservationCategory,
    PerceptualEvidence,
    PerceptualObservation,
    ResultState,
    ResultStatus,
    ScalarValue,
    TimeRange,
    UnitBasis,
)
from .context import (
    ListeningLevel,
    MonoCompatibility,
    PerceptualContext,
    PlaybackConstraint,
    PlaybackProfile,
    PlaybackProfileReference,
)
from .results import (
    PERCEPTUAL_SCHEMA_VERSION,
    AnalysisMetadata,
    FrequencyMaskingResult,
    MaskingEvent,
    PerceivedLoudnessResult,
    PerceptualAnalysisResult,
    PerceptualDescriptorResult,
    TranslationResult,
    TranslationRiskDimension,
    descriptor_observation,
)

__all__ = [
    "AUDITORY_FRONTEND_METHOD_ID",
    "AUDITORY_FRONTEND_METHOD_VERSION",
    "AUDITORY_FRONTEND_SCHEMA_VERSION",
    "PERCEPTUAL_SCHEMA_VERSION",
    "AnalysisMetadata",
    "AuditoryBand",
    "AuditoryFrontendConfig",
    "AuditoryFrontendSummary",
    "ComponentStatus",
    "Confidence",
    "ConfidenceBasis",
    "EvidenceSource",
    "FrequencyMaskingResult",
    "FrequencyRange",
    "ListeningLevel",
    "MaskingEvent",
    "Measurement",
    "MethodMetadata",
    "MonoCompatibility",
    "ObservationCategory",
    "PerceivedLoudnessResult",
    "PerceptualAnalysisResult",
    "PerceptualContext",
    "PerceptualDescriptorResult",
    "PerceptualEvidence",
    "PerceptualObservation",
    "PlaybackConstraint",
    "PlaybackProfile",
    "PlaybackProfileReference",
    "ResultState",
    "ResultStatus",
    "ScalarValue",
    "TimeRange",
    "TranslationResult",
    "TranslationRiskDimension",
    "UnitBasis",
    "descriptor_observation",
]
