from __future__ import annotations

"""Sprint 14 performance baseline and ONNX runtime benchmark foundation."""

from .benchmark import (
    BenchmarkMethod,
    aggregate_timed_samples,
    benchmark_callable,
    measure_latency,
)
from .contracts import (
    BenchmarkFingerprint,
    CompatibilityResult,
    DeviceType,
    EquivalenceKind,
    EquivalenceResult,
    EquivalenceStatus,
    LatencyStatistics,
    MemoryMeasurement,
    PerformanceBenchmarkResult,
    PerformanceEnvironment,
    PerformanceProfile,
    PerformanceWorkload,
    Precision,
    RawLatencySample,
    RejectedCandidate,
    RuntimeAvailabilityState,
    RuntimeBackend,
    RuntimeCandidate,
    RuntimeSelectionPolicy,
    RuntimeSelectionResult,
    SelectionStatus,
)
from .environment import capture_environment
from .runtime import (
    check_runtime_availability,
    evaluate_equivalence,
    runtime_fingerprint_fields,
    select_runtime,
)
from .workloads import (
    AuditoryFrontendWorkload,
    BrightnessDescriptorWorkload,
    ReferenceComparisonWorkload,
    build_workload_callables,
    make_synthetic_audio,
)

__all__ = [
    "AuditoryFrontendWorkload",
    "BenchmarkFingerprint",
    "BenchmarkMethod",
    "BrightnessDescriptorWorkload",
    "CompatibilityResult",
    "DeviceType",
    "EquivalenceKind",
    "EquivalenceResult",
    "EquivalenceStatus",
    "LatencyStatistics",
    "MemoryMeasurement",
    "PerformanceBenchmarkResult",
    "PerformanceEnvironment",
    "PerformanceProfile",
    "PerformanceWorkload",
    "Precision",
    "RawLatencySample",
    "ReferenceComparisonWorkload",
    "RejectedCandidate",
    "RuntimeAvailabilityState",
    "RuntimeBackend",
    "RuntimeCandidate",
    "RuntimeSelectionPolicy",
    "RuntimeSelectionResult",
    "SelectionStatus",
    "aggregate_timed_samples",
    "benchmark_callable",
    "build_workload_callables",
    "capture_environment",
    "check_runtime_availability",
    "evaluate_equivalence",
    "make_synthetic_audio",
    "measure_latency",
    "runtime_fingerprint_fields",
    "select_runtime",
]
