from __future__ import annotations

from .models import (
    AudioContext,
    AudioSemanticLabel,
)



class AudioClassifier:


    def classify(
        self,
        analysis,
        context,
        semantic=None,
    ) -> AudioContext:


        detected_elements = list(
            context.detected_elements
        )


        notes = list(
            context.notes
        )


        instrument = (
            context.instrument
        )


        confidence = (
            context.confidence
        )


        semantic_labels = []


        if semantic:


            top_labels = (
                semantic.top_labels(
                    limit=5
                )
            )


            print()

            print(
                "========== SEMANTIC LABELS =========="
            )


            for label in top_labels:


                print(
                    f"{label.name}: "
                    f"{label.confidence:.2f}"
                )


                semantic_labels.append(

                    AudioSemanticLabel(

                        name=label.name,

                        confidence=label.confidence,

                    )

                )


                if label.name not in detected_elements:

                    detected_elements.append(
                        label.name
                    )



            if top_labels:


                best = top_labels[0]


                confidence = max(
                    confidence,
                    best.confidence,
                )


                #
                # Only assign instrument
                # for stems/samples
                #

                if not context.is_full_mix:


                    if best.confidence >= 0.45:

                        instrument = (
                            best.name
                        )



                else:


                    notes.append(
                        "Semantic labels generated by CLAP for full mix analysis."
                    )



        return AudioContext(

            audio_type=context.audio_type,

            source_type=context.source_type,

            instrument=instrument,

            semantic_labels=semantic_labels,

            is_full_mix=context.is_full_mix,

            confidence=confidence,

            detected_elements=detected_elements,

            notes=notes,

        )